---
title: Quickstart Tutorial v2

datasources:
    my_db:
        plugin: mysql
        args:
            host: localhost
            user: ${USER}

views:
    num_users:
        cols: 4
        plugin: plot
        args:
            datasource: my_db
            query: select * from tutorial.new_users
            kind: bar
    total_users:
        title: Total new users
        cols: 2
        plugin: single_stat
        args:
            datasource: my_db
            query: select sum(num_new_users) from tutorial.new_users
    users_over_time:
        title: Users over time
        plugin: plot
        args:
            datasource: my_db
            query: |
                select `date`, (
                    select sum(num_new_users)
                    from tutorial.new_users u2 
                    where u2.`date` < u1.`date`
                ) as total_users
                from tutorial.new_users u1

outputs:
    html:
        plugin: static
        args:
            output_format: html
    png:
        plugin: static
        args:
            output_format: png