#!/usr/bin/env bash
set -e -u -o pipefail

python -m bash_kernel.install

echo "Configuring MySQL"
mkdir -p /tmp/mysql
cat >~/.my.cnf <<MY_CNF
[server]
datadir = /tmp/mysql
log-error = /tmp/mysql_error.log
socket = /tmp/mysql.sock
pid-file = /tmp/mysql.pid
# Specify as well in mysqld/mysql for distros
# that for some reason don't read [server]
[mysqld]
socket = /tmp/mysql.sock
[mysql]
socket = /tmp/mysql.sock
[client]
socket = /tmp/mysql.sock
MY_CNF
mysqld --initialize-insecure
mysqld &
echo "Waiting for MySQL to start"
while [[ ! -f /tmp/mysql.pid ]]; do sleep 1; done
echo "Creating local MySQL user"
mysql -u root <<SQL
create user '$NB_USER'@'localhost';
grant all privileges on *.* to '$NB_USER'@'localhost';
SQL
pkill -KILL mysqld
# Cleanup pid file manually
rm -f /tmp/mysql.pid
# Cleanup socket lockfile manually
rm -r /tmp/mysql.sock.lock

echo "Rebuilding font cache"
fc-cache -f -v
