---
title: Quickstart Tutorial

datasources:
    my_db:
        plugin: mysql
        args:
            host: tutorial_mysql
            user: ${DATABASE_USER}
            password: ${DATABASE_PASSWORD}
            
views:
    num_users:
        cols: 4
        plugin: plot
        args:
            datasource: my_db
            query: select * from tutorial.new_users
            kind: bar
    total_users:
        title: Total new users
        cols: 2
        plugin: single_stat
        args:
            datasource: my_db
            query: select sum(num_new_users) from tutorial.new_users
            
outputs:
    html:
        plugin: static
        args:
            output_dir: /out
