---
title: Quickstart Tutorial v2

datasources:
    my_db:
        plugin: mysql
        args:
            host: localhost
            user: ${USER}

views:
    num_users:
        cols: 4
        plugin: plot
        args:
            datasource: my_db
            query: select * from tutorial.new_users
            kind: bar
    total_users:
        title: Total new users
        cols: 2
        plugin: single_stat
        args:
            datasource: my_db
            query: select sum(num_new_users) from tutorial.new_users
    users_over_time:
        title: Users over time
        plugin: plot
        args:
            datasource: my_db
            query: |
                select `date`, sum(num_new_users) over (order by `date`) as total_users
                from tutorial.new_users

outputs:
    png:
        plugin: static
        args:
            output_format: png
    html:
        plugin: static
        args:
            output_format: html